### ISSUE TITLE
Option to enable open-svc in environment without browser

### ISSUE THREAD

**Issue by yoshwata** [superbrothers/kubectl-open-svc-plugin#75]
Thank you for making a great tool.

It would be nice to be able to open-svc even in an environment without a browser.
```
kubectl open-svc mysvc -p 9999 --address=dev.yoshwata.foo.jp
Opening service/mysvc in the default browser...
Error: exec: "xdg-open,x-www-browser,www-browser": executable file not found in $PATH
```
I want to access dev.yoshwata.foo.jp:9999 with a local browser after setting it to open-svc state on the remote server.

**Comment by superbrothers** [comment]
I would recommend opener. It is a tool that allows you to open a page in your local browser with `open` command on a remote server.

- https://github.com/superbrothers/opener

**Comment by yoshwata** [comment]
Thank you  @superbrothers . I understand that my suggestion is far from the open-svc concept. This issue will be closed.
